language: cpp
sudo: required

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq cmake libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update ;
        brew install sdl sdl_image sdl_mixer ;
    fi

script:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j2
